window.CUBO_DATA.plan.push(...[
  {
    "Priority": 6,
    "Article Title": "Arquitectura SEO para empresas de servicios: qué debe ser una landing y qué debe ser un artículo",
    "Pillar": "SEO / Web / Content",
    "Focus Keyword": "arquitectura SEO",
    "Secondary Keywords": "arquitectura web SEO; páginas de servicio SEO; intención de búsqueda; canibalización SEO; estructura web servicios",
    "Search Intent": "Informacional avanzada / comercial",
    "Buyer Persona": "Empresa de servicios con web grande, blog y páginas que se solapan",
    "Why Now": "Es una de las mejores expresiones del enfoque Cubo SEO: conectar intención, arquitectura, contenido y conversión.",
    "Evidence / Signal": "SERP 2026 muestra contenidos específicos sobre arquitectura para servicios y canibalización; la propia metodología de Cubo SEO trata este problema como prioritario.",
    "Differentiating Angle": "Cada URL necesita un trabajo: servicio, categoría, ubicación, comparación o contenido; no crear páginas por combinaciones de keywords.",
    "Recommended Length": "1,800–2,200",
    "Outline / H2s": "Por qué la arquitectura limita crecimiento | Mapa de intenciones | Roles de URL | Landing vs artículo vs categoría | Canibalización | Enlazado interno | Escalado por mercados/servicios | Ejemplo | Checklist | FAQs",
    "Internal Links": "/seo/; /diseno-y-desarrollo-web/; /marketing-de-contenidos/; /como-trabajamos/",
    "External Source 1": "https://developers.google.com/search/docs/essentials",
    "External Source 2": "https://developers.google.com/search/docs/crawling-indexing/canonicalization",
    "CTA": "Evaluar arquitectura e intención",
    "LinkedIn Angle": "Publicar más contenido no arregla una arquitectura que no sabe qué URL debe responder cada intención.",
    "Traffic Potential": 4,
    "Trend": 4,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 4,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 17
  },
  {
    "Priority": 7,
    "Article Title": "Search Console + GA4: cómo conectar visibilidad, comportamiento y conversiones",
    "Pillar": "Analytics / SEO",
    "Focus Keyword": "Search Console y Google Analytics",
    "Secondary Keywords": "Search Console GA4; conectar Search Console y GA4; SEO conversiones GA4; clicks vs sesiones",
    "Search Intent": "Tutorial / analítica",
    "Buyer Persona": "Marketing manager / SEO / dirección digital",
    "Why Now": "Permite explicar qué pasa antes y después del clic y sustenta reportes de negocio, no dashboards aislados.",
    "Evidence / Signal": "Google tiene documentación específica vigente sobre combinar Search Console y Google Analytics para SEO.",
    "Differentiating Angle": "Queries/páginas antes del clic + comportamiento/conversiones después del clic; aceptar discrepancias entre sistemas.",
    "Recommended Length": "1,500–1,800",
    "Outline / H2s": "Qué mide cada herramienta | Clicks vs sesiones | Cómo conectarlas | Qué preguntas responde el conjunto | Conversiones | Discrepancias | Dashboard mínimo | Ejemplos de decisiones | FAQs",
    "Internal Links": "/seo/; /como-trabajamos/; artículo branded/non-branded; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/monitor-debug/google-analytics-search-console",
    "External Source 2": "https://support.google.com/analytics/",
    "CTA": "Construir un reporting que ayude a decidir",
    "LinkedIn Angle": "Search Console y GA4 no deberían coincidir exactamente: miden partes distintas del mismo recorrido.",
    "Traffic Potential": 4,
    "Trend": 3,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 4,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 16
  },
  {
    "Priority": 8,
    "Article Title": "Core Web Vitals en 2026: qué importa para SEO, UX y conversiones",
    "Pillar": "Web / SEO",
    "Focus Keyword": "Core Web Vitals 2026",
    "Secondary Keywords": "Core Web Vitals SEO; LCP INP CLS; PageSpeed SEO; velocidad web SEO; rendimiento web",
    "Search Intent": "Informacional / técnico",
    "Buyer Persona": "Marketing / web manager / empresa preocupada por PageSpeed y SEO",
    "Why Now": "Tema evergreen con conversación técnica recurrente. Permite corregir la obsesión por '100/100' y conectar rendimiento con experiencia real.",
    "Evidence / Signal": "Google mantiene LCP, INP y CLS como Core Web Vitals y recomienda buena experiencia, pero aclara que una puntuación perfecta no garantiza rankings.",
    "Differentiating Angle": "Optimizar experiencia real, no perseguir un número de Lighthouse sin contexto.",
    "Recommended Length": "1,500–1,800",
    "Outline / H2s": "Qué son LCP/INP/CLS | Field vs lab | Relación con ranking | Qué afecta conversiones | Diagnóstico | WordPress | Qué arreglar primero | Cuándo dejar de optimizar | FAQs",
    "Internal Links": "/diseno-y-desarrollo-web/; /seo/; /como-trabajamos/",
    "External Source 1": "https://developers.google.com/search/docs/appearance/core-web-vitals",
    "External Source 2": "https://web.dev/vitals/",
    "CTA": "Evaluar rendimiento y experiencia de la web",
    "LinkedIn Angle": "Un 100/100 en Lighthouse no es una estrategia SEO: qué sí dicen Core Web Vitals.",
    "Traffic Potential": 5,
    "Trend": 3,
    "Commercial Fit": 4,
    "LinkedIn / Authority": 4,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 16
  },
  {
    "Priority": 9,
    "Article Title": "SEO internacional: hreflang, estructura de URLs y errores que bloquean una expansión",
    "Pillar": "SEO",
    "Focus Keyword": "SEO internacional",
    "Secondary Keywords": "hreflang SEO; web multilingüe SEO; SEO multiregional; estructura URLs idiomas; internacionalización SEO",
    "Search Intent": "Informacional avanzada / comercial",
    "Buyer Persona": "Empresa que opera o quiere operar en varios países o idiomas",
    "Why Now": "Filtra hacia empresas más maduras y encaja con la experiencia internacional de Cubo SEO. Puede llevar a proyectos de mayor valor.",
    "Evidence / Signal": "SERP específica para hreflang/SEO internacional y documentación oficial estable de Google sobre sitios multirregionales y multilingües.",
    "Differentiating Angle": "La traducción no es la estrategia: URLs, hreflang, localización, canonicals, mercado y medición.",
    "Recommended Length": "1,800–2,200",
    "Outline / H2s": "Cuándo necesitas SEO internacional | Mercado vs idioma | Estructuras de URL | hreflang | Canonicals | Localización | Contenido | Enlazado | Medición por país | Errores | FAQs",
    "Internal Links": "/seo/; /diseno-y-desarrollo-web/; /nuestro-trabajo/; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites",
    "External Source 2": "https://developers.google.com/search/docs/specialty/international/locale-adaptive-pages",
    "CTA": "Evaluar una expansión internacional",
    "LinkedIn Angle": "Traducir una web no crea una estrategia internacional: cinco decisiones SEO que deben resolverse antes.",
    "Traffic Potential": 4,
    "Trend": 3,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 4,
    "Confidence": "Media-Alta",
    "Status": "Pendiente",
    "Score / 20": 16
  },
  {
    "Priority": 10,
    "Article Title": "Del clic al lead: cómo conectar SEO, UX y customer journey",
    "Pillar": "SEO / UX / CRO",
    "Focus Keyword": "SEO y customer journey",
    "Secondary Keywords": "customer journey SEO; SEO UX CRO; búsqueda y conversión; intención de búsqueda customer journey",
    "Search Intent": "Educativa / estratégica",
    "Buyer Persona": "Marketing manager / empresa B2B o de servicios",
    "Why Now": "Resume el posicionamiento diferencial de Cubo SEO y tiene gran potencial de thought leadership aunque el volumen exacto sea N/D sin Semrush/Ahrefs.",
    "Evidence / Signal": "Google Trends muestra interés sostenido en UX/CRO y queries crecientes alrededor de customer journey; alta afinidad con el sistema de captación de Cubo SEO.",
    "Differentiating Angle": "El SEO no termina en el ranking: query → intención → landing → decisión → contacto → seguimiento.",
    "Recommended Length": "1,500–1,800",
    "Outline / H2s": "Por qué el ranking no basta | Query e intención | Landing y mensaje | Confianza | CTA/formulario | Fricción móvil | Seguimiento | Medición | Mapa del journey | FAQs",
    "Internal Links": "/seo/; /diseno-y-desarrollo-web/; /como-trabajamos/; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/monitor-debug/google-analytics-search-console",
    "External Source 2": "https://developers.google.com/search/docs/appearance/page-experience",
    "CTA": "Analizar el recorrido completo de captación",
    "LinkedIn Angle": "SEO puede traer al usuario correcto y aun así perderlo cinco segundos después: dónde termina Search y empieza el journey.",
    "Traffic Potential": 3,
    "Trend": 4,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 5,
    "Confidence": "Media-Alta",
    "Status": "Pendiente",
    "Score / 20": 17
  }
]);
