window.CUBO_DATA={plan:[
  {
    "Priority": 1,
    "Article Title": "Cómo medir tu visibilidad en AI Overviews y AI Mode con Search Console",
    "Pillar": "SEO / AI Search",
    "Focus Keyword": "Search Console AI Overviews",
    "Secondary Keywords": "Search Console AI Mode; medir visibilidad IA; impresiones AI Overviews; generative AI Search Console",
    "Search Intent": "Informacional avanzada",
    "Buyer Persona": "Marketing manager / Head of SEO / dirección digital",
    "Why Now": "El informe de IA generativa de Search Console se lanzó globalmente el 31/08/2026; es una oportunidad muy reciente y medible.",
    "Evidence / Signal": "Tendencia actual + fuente oficial; el blog ya cubre cómo aparecer en Search/IA, pero no un tutorial profundo de medición.",
    "Differentiating Angle": "No medir IA con screenshots: separar impresiones, páginas, países, dispositivos y evolución.",
    "Recommended Length": "1,400–1,700",
    "Outline / H2s": "Qué mide el informe | Dónde encontrarlo | Cómo leer impresiones/páginas/países/dispositivos | Limitaciones | Cómo combinarlo con Search normal | Qué decisiones tomar | FAQs",
    "Internal Links": "/seo/; artículo ChatGPT/AI Overviews; /como-trabajamos/; /contacto/",
    "External Source 1": "https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports",
    "External Source 2": "https://support.google.com/webmasters/answer/16984139",
    "CTA": "Evaluar visibilidad Search + AI",
    "LinkedIn Angle": "Google ya separa la visibilidad generativa en Search Console: qué cambia en la forma de medir SEO.",
    "Traffic Potential": 4,
    "Trend": 5,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 5,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 19
  },
  {
    "Priority": 2,
    "Article Title": "¿Tienes tráfico SEO pero no leads? Cómo encontrar dónde se rompe el recorrido",
    "Pillar": "SEO / CRO",
    "Focus Keyword": "tráfico orgánico no convierte",
    "Secondary Keywords": "SEO no genera leads; tráfico web no convierte; SEO conversiones; CRO SEO; tráfico orgánico leads",
    "Search Intent": "Problema / diagnóstico",
    "Buyer Persona": "Empresa con tráfico orgánico pero pocos contactos o ventas",
    "Why Now": "Ataca un dolor comercial directo y conecta SEO, UX, CRO, customer journey y medición: exactamente el posicionamiento de Cubo SEO.",
    "Evidence / Signal": "Google Trends muestra interés sostenido en UX/CRO; conversación pública recurrente sobre medir SEO más allá de clics.",
    "Differentiating Angle": "Diagnosticar el recorrido query → landing → mensaje → CTA → formulario → seguimiento, no pedir 'más tráfico' por defecto.",
    "Recommended Length": "1,600–2,000",
    "Outline / H2s": "Síntomas | Calidad de la demanda | Intención vs landing | Mensaje/oferta | UX y CTA | Formularios | Tracking | Follow-up | Framework de diagnóstico | FAQs",
    "Internal Links": "/seo/; /diseno-y-desarrollo-web/; /como-trabajamos/; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/monitor-debug/google-analytics-search-console",
    "External Source 2": "https://developers.google.com/search/docs/appearance/page-experience",
    "CTA": "Evaluar dónde se rompe el recorrido",
    "LinkedIn Angle": "El problema no siempre es falta de tráfico: 6 lugares donde un lead puede perderse después del clic.",
    "Traffic Potential": 4,
    "Trend": 4,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 5,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 18
  },
  {
    "Priority": 3,
    "Article Title": "Auditoría SEO: qué revisar primero y cómo priorizar lo que realmente importa",
    "Pillar": "SEO",
    "Focus Keyword": "auditoría SEO",
    "Secondary Keywords": "auditoría SEO técnica; checklist auditoría SEO; qué revisar en una auditoría SEO; prioridades SEO",
    "Search Intent": "Informacional / comercial",
    "Buyer Persona": "Empresa que necesita diagnóstico o ya recibió una auditoría llena de errores",
    "Why Now": "La SERP actual está muy activa y la intención conecta directamente con evaluación SEO. El diferenciador de Cubo SEO es priorizar por impacto, no por cantidad de avisos.",
    "Evidence / Signal": "SERP 2026 con múltiples guías recientes; Search Console y metodología de Cubo SEO refuerzan el ángulo de diagnóstico + prioridad.",
    "Differentiating Angle": "Una auditoría no es un PDF de 300 errores: contexto, bloqueos, oportunidades y orden de ejecución.",
    "Recommended Length": "1,800–2,200",
    "Outline / H2s": "Qué es una auditoría útil | Contexto de negocio | Rastreo/indexación | Arquitectura/intención | Contenido/enlazado | UX/CRO | Autoridad | Medición | Matriz impacto/esfuerzo/dependencias | Entregables | FAQs",
    "Internal Links": "/seo/; /como-trabajamos/; /nuestro-trabajo/; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/fundamentals/get-started",
    "External Source 2": "https://developers.google.com/search/docs/monitor-debug/search-console-start",
    "CTA": "Solicitar evaluación SEO",
    "LinkedIn Angle": "Lo más caro de una auditoría SEO no es encontrar errores; es arreglar primero los que no importan.",
    "Traffic Potential": 5,
    "Trend": 3,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 4,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 17
  },
  {
    "Priority": 4,
    "Article Title": "Rediseño web sin perder SEO: checklist antes, durante y después de una migración",
    "Pillar": "Web / SEO",
    "Focus Keyword": "rediseño web sin perder SEO",
    "Secondary Keywords": "migración web SEO; rediseño web SEO; cambiar web sin perder posicionamiento; checklist migración SEO",
    "Search Intent": "Informacional / comercial",
    "Buyer Persona": "Empresa que va a rediseñar, migrar de CMS, dominio o estructura",
    "Why Now": "Tiene clara proximidad a compra de desarrollo web y evita uno de los riesgos más costosos de un rediseño.",
    "Evidence / Signal": "SERP muy activa en 2026 y documentación oficial consolidada de Google sobre site moves y monitorización.",
    "Differentiating Angle": "Tratar el rediseño como migración controlada: inventario, paridad, redirects, QA y medición post-lanzamiento.",
    "Recommended Length": "1,800–2,200",
    "Outline / H2s": "Qué puede perderse | Inventario | Arquitectura/URLs | Staging | Contenido | Redirect map | Canonicals/hreflang | CWV | Lanzamiento | Search Console | Monitoreo 4–8 semanas | FAQs",
    "Internal Links": "/diseno-y-desarrollo-web/; /seo/; /como-trabajamos/; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes",
    "External Source 2": "https://developers.google.com/search/docs/crawling-indexing/site-move-no-url-changes",
    "CTA": "Planificar un rediseño con SEO desde el inicio",
    "LinkedIn Angle": "El SEO de una web no se 'migra al final': cinco decisiones que deben cerrarse antes de publicar el rediseño.",
    "Traffic Potential": 5,
    "Trend": 4,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 4,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 18
  },
  {
    "Priority": 5,
    "Article Title": "Cómo medir el ROI del SEO sin inventar atribución",
    "Pillar": "SEO / Analytics",
    "Focus Keyword": "ROI SEO",
    "Secondary Keywords": "cómo medir ROI SEO; retorno de inversión SEO; medir SEO; SEO conversiones; valor del tráfico orgánico",
    "Search Intent": "Informacional / ejecutiva",
    "Buyer Persona": "Founder / dirección / marketing manager que necesita justificar inversión SEO",
    "Why Now": "Tema muy cercano a decisión presupuestaria y a clientes de mayor tamaño. Permite diferenciar visibilidad, leads, pipeline y revenue sin prometer atribución perfecta.",
    "Evidence / Signal": "SERP activa en 2026; Google recomienda combinar Search Console y Analytics para relacionar descubrimiento con comportamiento y conversiones.",
    "Differentiating Angle": "ROI cuando el ciclo es largo: costos, conversiones, lead value, pipeline, revenue y límites de atribución.",
    "Recommended Length": "1,600–1,900",
    "Outline / H2s": "Qué significa ROI SEO | Costes reales | Qué medir antes del revenue | Search Console vs GA4 | Leads y valor | Atribución y ciclos largos | Modelo práctico | Errores | Dashboard ejecutivo | FAQs",
    "Internal Links": "/seo/; /como-trabajamos/; /nuestro-trabajo/; /contacto/",
    "External Source 1": "https://developers.google.com/search/docs/monitor-debug/google-analytics-search-console",
    "External Source 2": "https://support.google.com/analytics/",
    "CTA": "Revisar cómo estás midiendo SEO",
    "LinkedIn Angle": "Si el reporte SEO termina en clics e impresiones, todavía no responde la pregunta que hace dirección.",
    "Traffic Potential": 4,
    "Trend": 4,
    "Commercial Fit": 5,
    "LinkedIn / Authority": 5,
    "Confidence": "Alta",
    "Status": "Pendiente",
    "Score / 20": 18
  }
],reserves:[],evidence:[]};
